version: '3'
services:
  web-personas:
    container_name: personas
    build: .
    ports: ["####:####"]
    links:
      - db
    environment:
      - server.port=####
      - spring.datasource.url=jdbc:postgresql://####:####/personas-db
      - spring.datasource.username=personas
      - spring.datasource.password=123456
  db:
    container_name: data-pg
    image: postgres:latest
    ports: ["5433:5432"]
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=personas
      - POSTGRES_DB=personas-db

