version: '3.3'

services:
  web-provincias:
    container_name: provincias
    build: .
    ports: ["9191:9090"]
    depends_on:
      - "db"
    environment:
      - server.port=9090
      - spring.datasource.url=jdbc:mysql://data-provincias:3306/base-ejemplo
      - spring.datasource.username=usuario
      - spring.datasource.password=123456
  db:
    container_name: data-provincias
    image: mysql:latest
    environment: 
      MYSQL_DATABASE: 'base-ejemplo'
      MYSQL_USER: 'usuario'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: 'root'
    ports: 
      - '33060:3306'
    expose: 
      - '33060'
